pool:
  vmImage: 'windows-latest'

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
    
trigger: none
pr: none

steps:
- template: main.yml
  parameters:
    testClass: EWE*